import { config } from '@fohte/eslint-config'
import storybook from 'eslint-plugin-storybook'

export default config(
  {
    typescript: { typeChecked: true },
    errorHandling: {},
    tailwind: { cssConfigPath: 'web/src/index.css' },
  },
  { ignores: ['dist'] },
  ...storybook.configs['flat/recommended'],
  {
    // web/public/mockServiceWorker.js is generated by `msw init`; it must
    // not be linted or reformatted (see .prettierignore).
    ignores: ['web/public/mockServiceWorker.js'],
  },
  {
    // vite.config.ts/vitest.config.ts are loaded through Vite's own
    // esbuild-based config loader, which doesn't resolve the package.json
    // "imports" field, unlike the Rollup pipeline that bundles the app
    // itself. web/.storybook/vitest.setup.ts imports its sibling
    // web/.storybook/preview.ts by relative path because that file lives
    // outside src/, the only directory the "imports" field maps.
    files: [
      'web/.storybook/vitest.setup.ts',
      'web/vite.config.ts',
      'web/vitest.config.ts',
    ],
    rules: { 'no-restricted-imports': 'off' },
  },
)
